name: psi_ssm
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - scipy
  - netcdf4
  - ipykernel
  - geopandas
  - cartopy
  - cmocean
  - xarray
  - openpyxl
  - contextily
  - pyaml
  # Required in order to use process_netcdf to read multi-file datasets
  - dask
  # For improved performance using process_netcdf
  - h5netcdf
  - gsw
  # Recommend this one to prevent strange reprojection problems, but it consumes a lot of space
  - proj-data
